<#
.SYNOPSIS
    Automated Intune Detection Rule for Poly Studio
.DESCRIPTION
    Generated by CG Technology Intune App Packager.
    Standard Intune Exit Codes:
        exit 0 -> Application is installed
        exit 1 -> Application is NOT installed
#>

$appName    = "Poly Studio"
$appVersion = "5.1.0.1111"
$productCode = "{50E3D49D-AAA9-45B6-B16E-ED99645C8B71}"

# 1. Check Windows Uninstall Registry Keys (64-bit and 32-bit WOW64)
$registryPaths = @(
    "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*",
    "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
)

# Direct MSI ProductCode probe if available
if ($productCode) {
    $msiPaths = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$productCode",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\$productCode"
    )
    foreach ($mp in $msiPaths) {
        if (Test-Path $mp) {
            Write-Output "Found matching MSI ProductCode: $productCode"
            exit 0
        }
    }
}

# Inspect all registered installed applications
foreach ($regPath in $registryPaths) {
    $installedItems = Get-ItemProperty $regPath -ErrorAction SilentlyContinue | Where-Object {
        ($_.DisplayName -like "*$appName*") -or ($_.PSChildName -eq $productCode)
    }

    foreach ($item in $installedItems) {
        if ($item.DisplayName) {
            if ($appVersion) {
                # Check version comparison if version is specified
                if ($item.DisplayVersion -and ([System.Version]::TryParse($item.DisplayVersion, [ref]$null)) -and ([System.Version]::TryParse($appVersion, [ref]$null))) {
                    if ([System.Version]$item.DisplayVersion -ge [System.Version]$appVersion) {
                        Write-Output "Installed: $($item.DisplayName) (v$($item.DisplayVersion))"
                        exit 0
                    }
                } else {
                    Write-Output "Installed: $($item.DisplayName)"
                    exit 0
                }
            } else {
                Write-Output "Installed: $($item.DisplayName)"
                exit 0
            }
        }
    }
}

# 2. Application not detected
exit 1
